language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis Ci Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r kuang-springboot-service *
  - mkdir -p deploy
  - mv kuang-springboot-service.zip deploy/kuang-springboot-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kuang-springboot-service-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: kuang-springboot-service-bucket
    key: kuang-springboot-service.zip

    bundle_type: zip
    application: kaung-springboot-webservice

    deployment_group: kuang-springboot-webservice-group

    region: ap-northeast-2
    wait-until-deployed: true

# CI Complete
notifications:
  email:
    recipients:
      - guen9310@gmail.com