language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis Ci Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_install:
  - chmod +x gradlew

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/kuang-springboot-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kuang-springboot-service-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy # before_deploy dir
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kuang-springboot-service-bucket # S3 Bucket
    key: kuang-springboot-service.zip # Build File
    bundle_type: zip
    application: kaung-springboot-webservice # WEB Application
    deployment_group: kuang-springboot-webservice-group # Codedeploy Group
    region: ap-northeast-2
    wait-until-deployed: true

# CI Complete
notifications:
  email:
    recipients:
      - guen9310@gmail.com